// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrmybslplljtoqpgacwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybXlic2xwbGxqdG9xcGdhY3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1ODk0NDcsImV4cCI6MjA1MTE2NTQ0N30.Q12i5LI2LgiHkJYMc2OIYbHyX9KDVcNHgFtgmmU6pWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);